import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, useSession } from "next-auth/react";

import { useCallback, useEffect } from "react";
import Image from "next/image";

import { UserInfo } from "../components/UserInfo";
import { RecordForm } from "../components/RecordForm";
import { RecordsList } from "../components/RecordsList";
import { useTrpcContext } from "../hooks";

const Home: NextPage = () => {
  const {
    isUpdateRecordSuccess,
    isSetRecordSuccess,
    isDeleteRecordSuccess,
    refetchGetData,
  } = useTrpcContext();

  const { data: sessionData } = useSession();

  useEffect(() => {
    if (isSetRecordSuccess || isDeleteRecordSuccess || isUpdateRecordSuccess) {
      refetchGetData();
    }
  }, [
    isUpdateRecordSuccess,
    isSetRecordSuccess,
    isDeleteRecordSuccess,
    refetchGetData,
  ]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white dark:bg-slate-800">
        {sessionData?.user ? (
          <>
            <UserInfo />
            <div className="pt-4" />
            <RecordForm />
            <RecordsList />
          </>
        ) : (
          <button
            className="rounded-full bg-black/10 px-10 py-3 font-semibold text-black no-underline transition hover:bg-black/20"
            onClick={() => signIn()}
          >
            sign in
          </button>
        )}
      </main>
    </>
  );
};

export default Home;
