import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { useForm } from "react-hook-form";

import { trpc } from "../utils/trpc";
import { useCallback, useEffect } from "react";
import Image from "next/image";

import { UserInfo } from "../components/UserInfo";
import { RecordForm } from "../components/RecordForm";
import type { FormInputs } from "../types";

const Home: NextPage = () => {
  const { register, handleSubmit, reset } = useForm<FormInputs>({
    shouldUseNativeValidation: true,
  });

  const { data: sessionData } = useSession();
  const { mutate: setRecordMutation, isSuccess: isSetRecordSuccess } =
    trpc.record.setRecord.useMutation();
  const { mutate: setUpdateRecord, isSuccess: isUpdateRecordSuccess } =
    trpc.record.updateRecord.useMutation();

  const { mutate: setDeleteRecord, isSuccess: isDeleteRecordSuccess } =
    trpc.record.deleteRecord.useMutation();

  const { data: allRecords, refetch: refetchAllRecords } =
    trpc.record.getAll.useQuery(sessionData?.user?.id, {
      refetchInterval: false,
      refetchOnReconnect: false,
      refetchOnWindowFocus: false,
    });

  const { data: totalExpenseByCurrency, refetch: refetchTotalExpense } =
    trpc.record.totalExpense.useQuery(sessionData?.user?.id, {
      refetchInterval: false,
      refetchOnReconnect: false,
      refetchOnWindowFocus: false,
    });

  const onSubmit = async (data: FormInputs) => {
    if (!sessionData?.user?.id) {
      throw new Error("You are unauthorized");
    }
    setRecordMutation({ ...data, userId: sessionData?.user?.id });
    reset();
  };

  useEffect(() => {
    if (isSetRecordSuccess || isDeleteRecordSuccess) {
      refetchAllRecords();
      refetchTotalExpense();
    }
  }, [
    isSetRecordSuccess,
    isDeleteRecordSuccess,
    refetchAllRecords,
    refetchTotalExpense,
  ]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-400">
        {sessionData?.user ? (
          <>
            <UserInfo totalExpenseByCurrency={totalExpenseByCurrency} />
            <div className="pt-4" />
            <RecordForm
              register={register}
              handleSubmit={handleSubmit}
              onSubmit={onSubmit}
            />

            {allRecords
              ? allRecords.map((record) => (
                  <div key={record.id}>
                    <p>{record.name}</p>
                    <p>{record.message}</p>
                    <p>{record.amount}</p>
                    <p>{record.type}</p>
                    <p>{record.currency}</p>
                    <p>
                      {record.timestamp.getDate()}.{record.timestamp.getMonth()}
                    </p>
                    <button
                      className="rounded bg-blue-500 py-2 px-4 font-bold text-white hover:bg-blue-700"
                      onClick={() => setDeleteRecord(record.id)}
                    >
                      delete
                    </button>
                  </div>
                ))
              : null}
          </>
        ) : (
          <button
            className="rounded-full bg-black/10 px-10 py-3 font-semibold text-black no-underline transition hover:bg-black/20"
            onClick={() => signIn()}
          >
            sign in
          </button>
        )}
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  // console.log(sessionData);
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};

// export default AuthShowcase;
